# Generated by Django 6.0 on 2026-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentasDetallada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comprobante', models.CharField(max_length=5)),
                ('Descripcion_Comprobante', models.CharField(default='')),
                ('Letra', models.CharField(max_length=1)),
                ('Serie', models.IntegerField(default=0)),
                ('Numero', models.IntegerField()),
                ('Informado', models.CharField(max_length=2)),
                ('Motivo_Devolucion', models.IntegerField()),
                ('Descripcion_Motivo_Devolucion', models.CharField()),
                ('Fecha_Comprobante', models.DateField()),
                ('Sucursal', models.IntegerField()),
                ('Descripcion_Sucursal', models.CharField()),
                ('Vendedor', models.IntegerField()),
                ('Descripcion_Vendedor', models.CharField()),
                ('Numero_Pedido', models.IntegerField()),
                ('Cliente', models.IntegerField()),
                ('Razon_Social', models.CharField()),
                ('Zona', models.IntegerField()),
                ('Localidad', models.CharField()),
                ('Nro_Linea', models.IntegerField(default=1)),
                ('Codigo_Articulo', models.IntegerField()),
                ('Descripcion_Articulo', models.CharField()),
                ('Unidades_Bulto', models.IntegerField()),
                ('Categorias', models.IntegerField()),
                ('Descripcion_Categorias', models.CharField()),
                ('Familia', models.IntegerField()),
                ('Descripcion_Familia', models.CharField()),
                ('Costo_Neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('Bultos_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal_Neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('Subtotal_Final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('Canal', models.CharField()),
                ('IdCanal', models.BigIntegerField(default=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Comprobante', 'Letra', 'Serie', 'Numero', 'Nro_Linea', 'Codigo_Articulo'), name='unique_documento_articulo')],
            },
        ),
    ]
