# Generated by Django 6.0 on 2026-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroped', models.IntegerField()),
                ('idsucur', models.IntegerField(default=1)),
                ('iddessucur', models.CharField(default='', max_length=40)),
                ('idcliente', models.IntegerField(default=1)),
                ('idnomcliente', models.CharField(default='', max_length=100)),
                ('c_perso', models.IntegerField()),
                ('coddespercom', models.CharField(max_length=50)),
                ('fecentre', models.DateField()),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bonif', models.DecimalField(decimal_places=2, max_digits=14)),
                ('netogra', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nograva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codlipre', models.IntegerField()),
                ('coddeslipre', models.CharField(max_length=50)),
                ('ruta', models.IntegerField()),
                ('coddesruta', models.CharField(max_length=50)),
                ('iddocumento', models.CharField(max_length=6)),
                ('dsdocumento', models.CharField(max_length=20)),
                ('desccorta', models.CharField(max_length=15)),
                ('idrechazo', models.IntegerField()),
                ('preparado', models.BooleanField()),
                ('fecalta', models.DateField()),
                ('anulado', models.BooleanField()),
                ('facturado', models.BooleanField()),
                ('idmovcomercial', models.CharField(blank=True, max_length=20, null=True)),
                ('modificado', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('origen', models.CharField(max_length=30)),
                ('pickup', models.BooleanField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nroped', 'idsucur'), name='unique_nroped')],
            },
        ),
    ]
