# Generated by Django 6.0 on 2026-02-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codart', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('descrip', models.CharField(default='', max_length=100)),
                ('descripcat', models.CharField(default='', max_length=100)),
                ('marca', models.CharField(default='', max_length=50)),
                ('categoria', models.CharField(default='', max_length=30)),
                ('codbarra', models.CharField(default='', max_length=16)),
                ('anulado', models.BooleanField(default=False)),
                ('undxbulto', models.IntegerField(default=1)),
                ('minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('bulto', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pendiente', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('disponible', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('preciocomp', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('preciounicomp', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('posicion', models.IntegerField(default=0)),
                ('catalogo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlista', models.IntegerField()),
                ('descriplista', models.CharField(max_length=50)),
                ('anulado', models.BooleanField(default=False)),
                ('preciobase', models.DecimalField(decimal_places=3, max_digits=14)),
                ('preciofinal', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precioundbase', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precioundfinal', models.DecimalField(decimal_places=3, max_digits=14)),
                ('codart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idlista', 'codart'), name='unique_artxlista')],
            },
        ),
    ]
